management:
#  server:
#    port: 8081

  endpoint:
    health:
      probes:
        enabled: true

otel:
  exporter:
    otlp:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT}

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
